# coding: utf-8

"""
    Stytch

    This is the Stytch api.  You can find out more about Stytch at  [stytch.io](https://stytch.io).   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@stytch.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_update_name import UserUpdateName  # noqa: E501
from swagger_client.rest import ApiException


class TestUserUpdateName(unittest.TestCase):
    """UserUpdateName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserUpdateName(self):
        """Test UserUpdateName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_update_name.UserUpdateName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
