# coding: utf-8

"""
    Stytch

    This is the Stytch api.  You can find out more about Stytch at  [stytch.io](https://stytch.io).   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@stytch.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MagicLinkSendResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'magic_link_id': 'str',
        'method_id': 'str',
        'user_id': 'str'
    }

    attribute_map = {
        'magic_link_id': 'magic_link_id',
        'method_id': 'method_id',
        'user_id': 'user_id'
    }

    def __init__(self, magic_link_id=None, method_id=None, user_id=None):  # noqa: E501
        """MagicLinkSendResponse - a model defined in Swagger"""  # noqa: E501
        self._magic_link_id = None
        self._method_id = None
        self._user_id = None
        self.discriminator = None
        if magic_link_id is not None:
            self.magic_link_id = magic_link_id
        if method_id is not None:
            self.method_id = method_id
        if user_id is not None:
            self.user_id = user_id

    @property
    def magic_link_id(self):
        """Gets the magic_link_id of this MagicLinkSendResponse.  # noqa: E501


        :return: The magic_link_id of this MagicLinkSendResponse.  # noqa: E501
        :rtype: str
        """
        return self._magic_link_id

    @magic_link_id.setter
    def magic_link_id(self, magic_link_id):
        """Sets the magic_link_id of this MagicLinkSendResponse.


        :param magic_link_id: The magic_link_id of this MagicLinkSendResponse.  # noqa: E501
        :type: str
        """

        self._magic_link_id = magic_link_id

    @property
    def method_id(self):
        """Gets the method_id of this MagicLinkSendResponse.  # noqa: E501

        The method id for where to send the magic link, such as an email_id.  # noqa: E501

        :return: The method_id of this MagicLinkSendResponse.  # noqa: E501
        :rtype: str
        """
        return self._method_id

    @method_id.setter
    def method_id(self, method_id):
        """Sets the method_id of this MagicLinkSendResponse.

        The method id for where to send the magic link, such as an email_id.  # noqa: E501

        :param method_id: The method_id of this MagicLinkSendResponse.  # noqa: E501
        :type: str
        """

        self._method_id = method_id

    @property
    def user_id(self):
        """Gets the user_id of this MagicLinkSendResponse.  # noqa: E501


        :return: The user_id of this MagicLinkSendResponse.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this MagicLinkSendResponse.


        :param user_id: The user_id of this MagicLinkSendResponse.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MagicLinkSendResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MagicLinkSendResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
