# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import List, Optional

from stytch.b2b.models.organizations import Member, Organization
from stytch.b2b.models.sessions import MemberSession
from stytch.consumer.models.device_history import DeviceInfo
from stytch.core.response_base import ResponseBase


class GetResponse(ResponseBase):
    """Response type for `RecoveryCodes.get`.
    Fields:
      - member_id: Globally unique UUID that identifies a specific Member. When making API calls, you may use an `external_id` in place of the `member_id` if one is set for the member.
      - member: The Member object representing a user within a B2B organization, containing their profile information, authentication methods, roles, and registration details.
      - organization: The Organization object containing details about the B2B organization, including settings for SSO, authentication methods, MFA policies, and member management.
      - recovery_codes: The recovery codes used to authenticate the user without an authenticator app.
    """  # noqa

    member_id: str
    member: Member
    organization: Organization
    recovery_codes: List[str]


class RecoverResponse(ResponseBase):
    """Response type for `RecoveryCodes.recover`.
    Fields:
      - member_id: Globally unique UUID that identifies a specific Member. When making API calls, you may use an `external_id` in place of the `member_id` if one is set for the member.
      - member: The Member object representing a user within a B2B organization, containing their profile information, authentication methods, roles, and registration details.
      - organization: The Organization object containing details about the B2B organization, including settings for SSO, authentication methods, MFA policies, and member management.
      - session_token: The `session_token` associated with a Member's existing Session.
      - session_jwt: The JSON Web Token (JWT) associated with a Member's existing Session.
      - recovery_codes_remaining: The number of unused backup recovery codes available for MFA account recovery.
      - member_session: The MemberSession object containing details about an active authenticated session, including timing information, authentication factors used, and associated roles.
      - member_device: Information about the device used by the member for authentication, including device type, fingerprints, and location data.
    """  # noqa

    member_id: str
    member: Member
    organization: Organization
    session_token: str
    session_jwt: str
    recovery_codes_remaining: int
    member_session: Optional[MemberSession] = None
    member_device: Optional[DeviceInfo] = None


class RotateResponse(ResponseBase):
    """Response type for `RecoveryCodes.rotate`.
    Fields:
      - member_id: Globally unique UUID that identifies a specific Member. When making API calls, you may use an `external_id` in place of the `member_id` if one is set for the member.
      - member: The Member object representing a user within a B2B organization, containing their profile information, authentication methods, roles, and registration details.
      - organization: The Organization object containing details about the B2B organization, including settings for SSO, authentication methods, MFA policies, and member management.
      - recovery_codes: The recovery codes used to authenticate the user without an authenticator app.
    """  # noqa

    member_id: str
    member: Member
    organization: Organization
    recovery_codes: List[str]
