# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import List, Optional

import pydantic


class ConnectedApp(pydantic.BaseModel):
    """
    Fields:
      - client_id: The ID of the client.
      - client_name: A human-readable name for the client.
      - client_description: A human-readable description for the client.
      - status: The status of the entity.
      - full_access_allowed: Valid for first party clients only. If `true`, an authorization token granted to this client can be exchanged for a full Stytch Session.
      - client_type: The type of Connected App. Supported values are `first_party`, `first_party_public`, `third_party`, and `third_party_public`.
      - redirect_urls: Array of redirect URI values for use in OAuth Authorization flows.
      - access_token_expiry_minutes: The number of minutes until the access token expires.
      - access_token_template_content: A template string defining the structure and custom claims to include in generated access tokens.
      - post_logout_redirect_urls: A list of allowed URLs to which users can be redirected after logging out.
      - bypass_consent_for_offline_access: A boolean flag indicating whether to skip the consent screen when requesting offline_access scope for refresh tokens.
      - client_secret_last_four: The last four characters of the current client secret, used for identification without exposing the full secret.
      - next_client_secret_last_four: The last four characters of the next client secret, used during secret rotation.
      - access_token_custom_audience: A custom audience (aud) claim value to include in the generated access token JWT.
      - logo_url: The URL of the logo image for the organization, SSO connection, or connected application.
      - client_id_metadata_url: The URL of the OAuth client metadata endpoint for dynamic client configuration.
    """  # noqa

    client_id: str
    client_name: str
    client_description: str
    status: str
    full_access_allowed: bool
    client_type: str
    redirect_urls: List[str]
    access_token_expiry_minutes: int
    access_token_template_content: str
    post_logout_redirect_urls: List[str]
    bypass_consent_for_offline_access: bool
    client_secret_last_four: Optional[str] = None
    next_client_secret_last_four: Optional[str] = None
    access_token_custom_audience: Optional[str] = None
    logo_url: Optional[str] = None
    client_id_metadata_url: Optional[str] = None


class ConnectedAppPublic(pydantic.BaseModel):
    """
    Fields:
      - client_id: The ID of the client.
      - client_name: A human-readable name for the client.
      - client_description: A human-readable description for the client.
      - client_type: The type of Connected App. Supported values are `first_party`, `first_party_public`, `third_party`, and `third_party_public`.
      - logo_url: The URL of the logo image for the organization, SSO connection, or connected application.
    """  # noqa

    client_id: str
    client_name: str
    client_description: str
    client_type: str
    logo_url: Optional[str] = None


class ConnectedAppWithClientSecret(pydantic.BaseModel):
    """
    Fields:
      - client_id: The ID of the client.
      - client_name: A human-readable name for the client.
      - client_description: A human-readable description for the client.
      - status: The status of the entity.
      - full_access_allowed: Valid for first party clients only. If `true`, an authorization token granted to this client can be exchanged for a full Stytch Session.
      - client_type: The type of Connected App. Supported values are `first_party`, `first_party_public`, `third_party`, and `third_party_public`.
      - redirect_urls: Array of redirect URI values for use in OAuth Authorization flows.
      - access_token_expiry_minutes: The number of minutes until the access token expires.
      - access_token_template_content: A template string defining the structure and custom claims to include in generated access tokens.
      - post_logout_redirect_urls: A list of allowed URLs to which users can be redirected after logging out.
      - bypass_consent_for_offline_access: A boolean flag indicating whether to skip the consent screen when requesting offline_access scope for refresh tokens.
      - client_secret_last_four: The last four characters of the current client secret, used for identification without exposing the full secret.
      - next_client_secret_last_four: The last four characters of the next client secret, used during secret rotation.
      - client_secret: The secret belonging to the OAuth2.0 client used to authenticate login attempts. This will be provided by the IdP.
      - access_token_custom_audience: A custom audience (aud) claim value to include in the generated access token JWT.
      - logo_url: The URL of the logo image for the organization, SSO connection, or connected application.
      - client_id_metadata_url: The URL of the OAuth client metadata endpoint for dynamic client configuration.
    """  # noqa

    client_id: str
    client_name: str
    client_description: str
    status: str
    full_access_allowed: bool
    client_type: str
    redirect_urls: List[str]
    access_token_expiry_minutes: int
    access_token_template_content: str
    post_logout_redirect_urls: List[str]
    bypass_consent_for_offline_access: bool
    client_secret_last_four: Optional[str] = None
    next_client_secret_last_four: Optional[str] = None
    client_secret: Optional[str] = None
    access_token_custom_audience: Optional[str] = None
    logo_url: Optional[str] = None
    client_id_metadata_url: Optional[str] = None


class ConnectedAppWithNextClientSecret(pydantic.BaseModel):
    """
    Fields:
      - client_id: The ID of the client.
      - client_name: A human-readable name for the client.
      - client_description: A human-readable description for the client.
      - status: The status of the entity.
      - client_secret_last_four: The last four characters of the current client secret, used for identification without exposing the full secret.
      - full_access_allowed: Valid for first party clients only. If `true`, an authorization token granted to this client can be exchanged for a full Stytch Session.
      - client_type: The type of Connected App. Supported values are `first_party`, `first_party_public`, `third_party`, and `third_party_public`.
      - redirect_urls: Array of redirect URI values for use in OAuth Authorization flows.
      - next_client_secret: The next client secret to be used after secret rotation is complete. **Important:** this is the only time you will be able to view the `client_secret`. Be sure to persist its value in a secure location. If the `client_secret` is lost, you will need to trigger a secret rotation flow to receive another one.
      - access_token_expiry_minutes: The number of minutes until the access token expires.
      - access_token_template_content: A template string defining the structure and custom claims to include in generated access tokens.
      - post_logout_redirect_urls: A list of allowed URLs to which users can be redirected after logging out.
      - bypass_consent_for_offline_access: A boolean flag indicating whether to skip the consent screen when requesting offline_access scope for refresh tokens.
      - next_client_secret_last_four: The last four characters of the next client secret, used during secret rotation.
      - access_token_custom_audience: A custom audience (aud) claim value to include in the generated access token JWT.
      - logo_url: The URL of the logo image for the organization, SSO connection, or connected application.
      - client_id_metadata_url: The URL of the OAuth client metadata endpoint for dynamic client configuration.
    """  # noqa

    client_id: str
    client_name: str
    client_description: str
    status: str
    client_secret_last_four: str
    full_access_allowed: bool
    client_type: str
    redirect_urls: List[str]
    next_client_secret: str
    access_token_expiry_minutes: int
    access_token_template_content: str
    post_logout_redirect_urls: List[str]
    bypass_consent_for_offline_access: bool
    next_client_secret_last_four: Optional[str] = None
    access_token_custom_audience: Optional[str] = None
    logo_url: Optional[str] = None
    client_id_metadata_url: Optional[str] = None


class ResultsMetadata(pydantic.BaseModel):
    """
    Fields:
      - total: The total count of items or results in a paginated response or collection.
      - next_cursor: A cursor value for fetching the next page of paginated results.
    """  # noqa

    total: int
    next_cursor: Optional[str] = None
