# !!!
# WARNING: This file is autogenerated
# Only modify code within MANUAL() sections
# or your changes may be overwritten later!
# !!!

from __future__ import annotations

from typing import List, Optional

import pydantic

from stytch.core.response_base import ResponseBase


class PolicyResource(pydantic.BaseModel):
    """
    Fields:
      - resource_id: A unique identifier of the RBAC Resource, provided by the developer and intended to be human-readable. A `resource_id` is not allowed to start with `stytch`, which is a special prefix used for Stytch default Resources with reserved `resource_id`s.
      - description: A human-readable description of the RBAC resource, role, or scope that explains its purpose and permissions.
      - actions: An array of actions that can be performed on the given resource.
    """  # noqa

    resource_id: str
    description: str
    actions: List[str]


class PolicyRolePermission(pydantic.BaseModel):
    """
    Fields:
      - resource_id: A unique identifier of the RBAC Resource, provided by the developer and intended to be human-readable. A `resource_id` is not allowed to start with `stytch`, which is a special prefix used for Stytch default Resources with reserved `resource_id`s.
      - actions: An array of actions that can be performed on the given resource.
    """  # noqa

    resource_id: str
    actions: List[str]


class PolicyRole(pydantic.BaseModel):
    """
    Fields:
      - role_id: The unique identifier for an RBAC role.
      - description: A human-readable description of the RBAC resource, role, or scope that explains its purpose and permissions.
      - permissions: A list of RBAC permissions defining specific actions that can be performed on resources.
    """  # noqa

    role_id: str
    description: str
    permissions: List[PolicyRolePermission]


class PolicyScopePermission(pydantic.BaseModel):
    """
    Fields:
      - resource_id: A unique identifier of the RBAC Resource, provided by the developer and intended to be human-readable. A `resource_id` is not allowed to start with `stytch`, which is a special prefix used for Stytch default Resources with reserved `resource_id`s.
      - actions: An array of actions that can be performed on the given resource.
    """  # noqa

    resource_id: str
    actions: List[str]


class PolicyScope(pydantic.BaseModel):
    """
    Fields:
      - scope: A space-separated string of OAuth scopes defining requested permissions.
      - description: A human-readable description of the RBAC resource, role, or scope that explains its purpose and permissions.
      - permissions: A list of RBAC permissions defining specific actions that can be performed on resources.
    """  # noqa

    scope: str
    description: str
    permissions: List[PolicyScopePermission]


class Policy(pydantic.BaseModel):
    """
    Fields:
      - roles: An array of [Role objects](https://stytch.com/docs/api/rbac-role-object).
      - resources: A list of RBAC resources that define what entities can be accessed or modified, used in authorization policies.
      - scopes: An array of scopes available in the policy.
    """  # noqa

    roles: List[PolicyRole]
    resources: List[PolicyResource]
    scopes: List[PolicyScope]


class PolicyResponse(ResponseBase):
    """Response type for `RBAC.policy`.
    Fields:
      - policy: The RBAC Policy document that contains all defined Roles and Resources.
    """  # noqa

    policy: Optional[Policy] = None
