# coding: utf-8

"""
    Stytch

    This is the Stytch api.  You can find out more about Stytch at  [stytch.com](https://stytch.com).   # noqa: E501

    The version of the OpenAPI document: v1
    Contact: hello@stytch.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from stytch.configuration import Configuration


class MagicLinkAuthenticateOptions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ip_match_required': 'bool',
        'user_agent_match_required': 'bool'
    }

    attribute_map = {
        'ip_match_required': 'ip_match_required',
        'user_agent_match_required': 'user_agent_match_required'
    }

    def __init__(self, ip_match_required=None, user_agent_match_required=None, local_vars_configuration=None):  # noqa: E501
        """MagicLinkAuthenticateOptions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._ip_match_required = None
        self._user_agent_match_required = None
        self.discriminator = None

        if ip_match_required is not None:
            self.ip_match_required = ip_match_required
        if user_agent_match_required is not None:
            self.user_agent_match_required = user_agent_match_required

    @property
    def ip_match_required(self):
        """Gets the ip_match_required of this MagicLinkAuthenticateOptions.  # noqa: E501

        Require that the ip address the magic link was requested from matches the ip address it's clicked from.  # noqa: E501

        :return: The ip_match_required of this MagicLinkAuthenticateOptions.  # noqa: E501
        :rtype: bool
        """
        return self._ip_match_required

    @ip_match_required.setter
    def ip_match_required(self, ip_match_required):
        """Sets the ip_match_required of this MagicLinkAuthenticateOptions.

        Require that the ip address the magic link was requested from matches the ip address it's clicked from.  # noqa: E501

        :param ip_match_required: The ip_match_required of this MagicLinkAuthenticateOptions.  # noqa: E501
        :type: bool
        """

        self._ip_match_required = ip_match_required

    @property
    def user_agent_match_required(self):
        """Gets the user_agent_match_required of this MagicLinkAuthenticateOptions.  # noqa: E501

        Require that the user agent the magic link was requested from matches the user agent it's clicked from.  # noqa: E501

        :return: The user_agent_match_required of this MagicLinkAuthenticateOptions.  # noqa: E501
        :rtype: bool
        """
        return self._user_agent_match_required

    @user_agent_match_required.setter
    def user_agent_match_required(self, user_agent_match_required):
        """Sets the user_agent_match_required of this MagicLinkAuthenticateOptions.

        Require that the user agent the magic link was requested from matches the user agent it's clicked from.  # noqa: E501

        :param user_agent_match_required: The user_agent_match_required of this MagicLinkAuthenticateOptions.  # noqa: E501
        :type: bool
        """

        self._user_agent_match_required = user_agent_match_required

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MagicLinkAuthenticateOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MagicLinkAuthenticateOptions):
            return True

        return self.to_dict() != other.to_dict()
