name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-stytch:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    name: "Run tests for python ${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check types
        run: mypy stytch codegen test

      - name: Run unit tests
        run: python -m unittest
