name: Pull Request checks

on:
  pull_request:
    branches: [main]

jobs:
  test-stytch:
    runs-on: ubuntu-latest

    name: "Run linter and tests"
    steps:
      - uses: stytchauth/stytch-python/.github/workflows/lint-and-test.yaml
